#!/usr/sbin/nft -f
# Slate OS firewall — default deny inbound, allow all outbound
flush ruleset

table inet filter {
  chain input {
    type filter hook input priority filter; policy drop;
    iif lo accept
    ct state invalid drop
    ct state { established, related } accept
    meta l4proto { icmp, ipv6-icmp } accept
    udp dport { 67, 68 } accept comment "DHCP"
  }
  chain output {
    type filter hook output priority filter; policy accept;
  }
  chain forward {
    type filter hook forward priority filter; policy drop;
  }
}
