/// File generators for the extracted palette.
///
/// Each writer serialises a `Palette` into a format consumed by a different
/// part of the desktop stack. All writers use atomic writes (temp file + rename)
/// and create parent directories as needed.
use std::io::Write;
use std::path::Path;

use anyhow::{Context, Result};
use slate_common::Palette;

/// Helper: write `content` atomically to `path` (write temp + rename).
fn atomic_write(path: &Path, content: &[u8]) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create dirs for {}", path.display()))?;
    }

    // Write to a sibling temp file in the same directory so rename is atomic.
    let temp_path = path.with_extension("tmp");
    let mut f = std::fs::File::create(&temp_path)
        .with_context(|| format!("create temp file {}", temp_path.display()))?;
    f.write_all(content)
        .with_context(|| format!("write temp file {}", temp_path.display()))?;
    f.flush()?;

    std::fs::rename(&temp_path, path)
        .with_context(|| format!("rename {} -> {}", temp_path.display(), path.display()))?;

    Ok(())
}

/// Format an `[R, G, B, A]` colour as `rgba(R, G, B, A)` with A normalised to 0.0-1.0.
fn rgba_str(c: [u8; 4]) -> String {
    let alpha = f64::from(c[3]) / 255.0;
    // Use two decimal places; trim trailing zeros for cleanliness.
    let alpha_str = format!("{alpha:.2}");
    format!("rgba({}, {}, {}, {})", c[0], c[1], c[2], alpha_str)
}

// ---------------------------------------------------------------------------
// TOML
// ---------------------------------------------------------------------------

/// Serialise palette to TOML and write to `path`.
///
/// Output: `~/.config/slate/palette.toml`
pub fn write_palette_toml(palette: &Palette, path: &Path) -> Result<()> {
    let content = toml::to_string_pretty(palette).context("serialise palette to TOML")?;
    atomic_write(path, content.as_bytes())?;
    tracing::info!("wrote palette.toml to {}", path.display());
    Ok(())
}

// ---------------------------------------------------------------------------
// CSS (@define-color for GTK / Waybar)
// ---------------------------------------------------------------------------

/// Serialise palette to GTK `@define-color` CSS and write to `path`.
///
/// Output: `~/.config/slate/palette.css`
pub fn write_palette_css(palette: &Palette, path: &Path) -> Result<()> {
    let content = format!(
        "\
@define-color slate_primary {};
@define-color slate_secondary {};
@define-color slate_surface {};
@define-color slate_container {};
@define-color slate_neutral {};
",
        rgba_str(palette.primary),
        rgba_str(palette.secondary),
        rgba_str(palette.surface),
        rgba_str(palette.container),
        rgba_str(palette.neutral),
    );
    atomic_write(path, content.as_bytes())?;
    tracing::info!("wrote palette.css to {}", path.display());
    Ok(())
}

// ---------------------------------------------------------------------------
// KDL (Niri border colours)
// ---------------------------------------------------------------------------

/// Serialise palette to a Niri KDL border-colour snippet and write to `path`.
///
/// The inactive colour uses the neutral colour with alpha dimmed to ~40%.
/// Output: `~/.config/niri/palette.kdl`
pub fn write_palette_kdl(palette: &Palette, path: &Path) -> Result<()> {
    let active = rgba_str(palette.primary);
    let mut dimmed_neutral = palette.neutral;
    dimmed_neutral[3] = 102; // ~40% of 255
    let inactive = rgba_str(dimmed_neutral);

    let content = format!(
        "\
// Auto-generated by slate-palette — do not edit
border {{
    active-color \"{active}\"
    inactive-color \"{inactive}\"
}}
"
    );
    atomic_write(path, content.as_bytes())?;
    tracing::info!("wrote palette.kdl to {}", path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_palette() -> Palette {
        Palette {
            primary: [100, 149, 237, 255],
            secondary: [138, 180, 248, 255],
            surface: [18, 18, 24, 255],
            container: [30, 30, 40, 255],
            neutral: [228, 228, 232, 255],
        }
    }

    #[test]
    fn rgba_str_fully_opaque() {
        assert_eq!(rgba_str([255, 0, 128, 255]), "rgba(255, 0, 128, 1.00)");
    }

    #[test]
    fn rgba_str_partial_alpha() {
        assert_eq!(rgba_str([10, 20, 30, 128]), "rgba(10, 20, 30, 0.50)");
    }

    #[test]
    fn write_palette_toml_round_trips() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("palette.toml");
        let palette = test_palette();

        write_palette_toml(&palette, &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        let loaded: Palette = toml::from_str(&content).unwrap();
        assert_eq!(palette, loaded);
    }

    #[test]
    fn write_palette_toml_creates_parent_dirs() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("deep").join("nested").join("palette.toml");

        write_palette_toml(&test_palette(), &path).unwrap();
        assert!(path.exists());
    }

    #[test]
    fn write_palette_css_format() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("palette.css");
        let palette = test_palette();

        write_palette_css(&palette, &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("@define-color slate_primary rgba(100, 149, 237, 1.00);"));
        assert!(content.contains("@define-color slate_secondary rgba(138, 180, 248, 1.00);"));
        assert!(content.contains("@define-color slate_surface rgba(18, 18, 24, 1.00);"));
        assert!(content.contains("@define-color slate_container rgba(30, 30, 40, 1.00);"));
        assert!(content.contains("@define-color slate_neutral rgba(228, 228, 232, 1.00);"));
    }

    #[test]
    fn write_palette_css_has_five_lines() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("palette.css");

        write_palette_css(&test_palette(), &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        let define_count = content.matches("@define-color").count();
        assert_eq!(define_count, 5, "expected 5 @define-color declarations");
    }

    #[test]
    fn write_palette_kdl_format() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("palette.kdl");
        let palette = test_palette();

        write_palette_kdl(&palette, &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("// Auto-generated by slate-palette"));
        assert!(content.contains("border {"));
        assert!(content.contains("active-color \"rgba(100, 149, 237, 1.00)\""));
        // Neutral with dimmed alpha (~40% = 102/255 ≈ 0.40)
        assert!(content.contains("inactive-color \"rgba(228, 228, 232, 0.40)\""));
    }

    #[test]
    fn write_palette_kdl_has_border_block() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("palette.kdl");

        write_palette_kdl(&test_palette(), &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("border {"), "missing border block");
        assert!(content.contains('}'), "missing closing brace");
    }

    #[test]
    fn atomic_write_creates_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.txt");
        atomic_write(&path, b"hello").unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "hello");
    }

    #[test]
    fn atomic_write_overwrites_existing() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.txt");
        atomic_write(&path, b"first").unwrap();
        atomic_write(&path, b"second").unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "second");
    }
}
